/**
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApChallengeMicroservice) {
      root.ApChallengeMicroservice = {};
    }
    root.ApChallengeMicroservice.DirectPrize = factory(root.ApChallengeMicroservice.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DirectPrize model module.
   * @module model/DirectPrize
   * @version 1.0.5
   */

  /**
   * Constructs a new <code>DirectPrize</code>.
   * @alias module:model/DirectPrize
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>DirectPrize</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DirectPrize} obj Optional instance to populate.
   * @return {module:model/DirectPrize} The populated <code>DirectPrize</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('placement')) {
        obj['placement'] = ApiClient.convertToType(data['placement'], 'Integer');
      }
      if (data.hasOwnProperty('prizeAmount')) {
        obj['prizeAmount'] = ApiClient.convertToType(data['prizeAmount'], 'Integer');
      }
      if (data.hasOwnProperty('prizeType')) {
        obj['prizeType'] = ApiClient.convertToType(data['prizeType'], 'Integer');
      }
      if (data.hasOwnProperty('challengeId')) {
        obj['challengeId'] = ApiClient.convertToType(data['challengeId'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Integer} placement
   */
  exports.prototype['placement'] = undefined;
  /**
   * @member {Integer} prizeAmount
   */
  exports.prototype['prizeAmount'] = undefined;
  /**
   * @member {Integer} prizeType
   */
  exports.prototype['prizeType'] = undefined;
  /**
   * @member {Integer} challengeId
   */
  exports.prototype['challengeId'] = undefined;



  return exports;
}));


