/**
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2001ResultSubmissions'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse2001ResultSubmissions'));
  } else {
    // Browser globals (root is window)
    if (!root.ApChallengeMicroservice) {
      root.ApChallengeMicroservice = {};
    }
    root.ApChallengeMicroservice.InlineResponse2006ResultUserDetails = factory(root.ApChallengeMicroservice.ApiClient, root.ApChallengeMicroservice.InlineResponse2001ResultSubmissions);
  }
}(this, function(ApiClient, InlineResponse2001ResultSubmissions) {
  'use strict';




  /**
   * The InlineResponse2006ResultUserDetails model module.
   * @module model/InlineResponse2006ResultUserDetails
   * @version 1.0.5
   */

  /**
   * Constructs a new <code>InlineResponse2006ResultUserDetails</code>.
   * @alias module:model/InlineResponse2006ResultUserDetails
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>InlineResponse2006ResultUserDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2006ResultUserDetails} obj Optional instance to populate.
   * @return {module:model/InlineResponse2006ResultUserDetails} The populated <code>InlineResponse2006ResultUserDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('roles')) {
        obj['roles'] = ApiClient.convertToType(data['roles'], ['String']);
      }
      if (data.hasOwnProperty('hasUserSubmittedForReview')) {
        obj['hasUserSubmittedForReview'] = ApiClient.convertToType(data['hasUserSubmittedForReview'], 'Boolean');
      }
      if (data.hasOwnProperty('submissionReviewScore')) {
        obj['submissionReviewScore'] = ApiClient.convertToType(data['submissionReviewScore'], 'Integer');
      }
      if (data.hasOwnProperty('winningPlacements')) {
        obj['winningPlacements'] = ApiClient.convertToType(data['winningPlacements'], 'Integer');
      }
      if (data.hasOwnProperty('submissions')) {
        obj['submissions'] = ApiClient.convertToType(data['submissions'], [InlineResponse2001ResultSubmissions]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<String>} roles
   */
  exports.prototype['roles'] = undefined;
  /**
   * @member {Boolean} hasUserSubmittedForReview
   */
  exports.prototype['hasUserSubmittedForReview'] = undefined;
  /**
   * @member {Integer} submissionReviewScore
   */
  exports.prototype['submissionReviewScore'] = undefined;
  /**
   * @member {Integer} winningPlacements
   */
  exports.prototype['winningPlacements'] = undefined;
  /**
   * @member {Array.<module:model/InlineResponse2001ResultSubmissions>} submissions
   */
  exports.prototype['submissions'] = undefined;



  return exports;
}));


