/**
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApChallengeMicroservice) {
      root.ApChallengeMicroservice = {};
    }
    root.ApChallengeMicroservice.InlineResponse2002ResultContentWinners = factory(root.ApChallengeMicroservice.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineResponse2002ResultContentWinners model module.
   * @module model/InlineResponse2002ResultContentWinners
   * @version 1.0.5
   */

  /**
   * Constructs a new <code>InlineResponse2002ResultContentWinners</code>.
   * @alias module:model/InlineResponse2002ResultContentWinners
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>InlineResponse2002ResultContentWinners</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2002ResultContentWinners} obj Optional instance to populate.
   * @return {module:model/InlineResponse2002ResultContentWinners} The populated <code>InlineResponse2002ResultContentWinners</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('submissionId')) {
        obj['submissionId'] = ApiClient.convertToType(data['submissionId'], 'Number');
      }
      if (data.hasOwnProperty('submitter')) {
        obj['submitter'] = ApiClient.convertToType(data['submitter'], 'String');
      }
      if (data.hasOwnProperty('submissionTime')) {
        obj['submissionTime'] = ApiClient.convertToType(data['submissionTime'], 'Date');
      }
      if (data.hasOwnProperty('rank')) {
        obj['rank'] = ApiClient.convertToType(data['rank'], 'Integer');
      }
      if (data.hasOwnProperty('points')) {
        obj['points'] = ApiClient.convertToType(data['points'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * @member {Number} submissionId
   */
  exports.prototype['submissionId'] = undefined;
  /**
   * @member {String} submitter
   */
  exports.prototype['submitter'] = undefined;
  /**
   * @member {Date} submissionTime
   */
  exports.prototype['submissionTime'] = undefined;
  /**
   * @member {Integer} rank
   */
  exports.prototype['rank'] = undefined;
  /**
   * @member {Integer} points
   */
  exports.prototype['points'] = undefined;



  return exports;
}));


