/**
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2008ResultRounds'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse2008ResultRounds'));
  } else {
    // Browser globals (root is window)
    if (!root.ApChallengeMicroservice) {
      root.ApChallengeMicroservice = {};
    }
    root.ApChallengeMicroservice.InlineResponse2008ResultContent = factory(root.ApChallengeMicroservice.ApiClient, root.ApChallengeMicroservice.InlineResponse2008ResultRounds);
  }
}(this, function(ApiClient, InlineResponse2008ResultRounds) {
  'use strict';




  /**
   * The InlineResponse2008ResultContent model module.
   * @module model/InlineResponse2008ResultContent
   * @version 1.0.5
   */

  /**
   * Constructs a new <code>InlineResponse2008ResultContent</code>.
   * @alias module:model/InlineResponse2008ResultContent
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>InlineResponse2008ResultContent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2008ResultContent} obj Optional instance to populate.
   * @return {module:model/InlineResponse2008ResultContent} The populated <code>InlineResponse2008ResultContent</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('startDate')) {
        obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Date');
      }
      if (data.hasOwnProperty('endDate')) {
        obj['endDate'] = ApiClient.convertToType(data['endDate'], 'Date');
      }
      if (data.hasOwnProperty('track')) {
        obj['track'] = ApiClient.convertToType(data['track'], 'String');
      }
      if (data.hasOwnProperty('subTrack')) {
        obj['subTrack'] = ApiClient.convertToType(data['subTrack'], 'String');
      }
      if (data.hasOwnProperty('numRegistrants')) {
        obj['numRegistrants'] = ApiClient.convertToType(data['numRegistrants'], ['Number']);
      }
      if (data.hasOwnProperty('rounds')) {
        obj['rounds'] = ApiClient.convertToType(data['rounds'], [InlineResponse2008ResultRounds]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * ISO-8601 formatted date times (YYYY-MM-DDTHH:mm:ss.sssZ)
   * @member {Date} startDate
   */
  exports.prototype['startDate'] = undefined;
  /**
   * ISO-8601 formatted date times (YYYY-MM-DDTHH:mm:ss.sssZ)
   * @member {Date} endDate
   */
  exports.prototype['endDate'] = undefined;
  /**
   * @member {String} track
   */
  exports.prototype['track'] = undefined;
  /**
   * @member {String} subTrack
   */
  exports.prototype['subTrack'] = undefined;
  /**
   * @member {Array.<Number>} numRegistrants
   */
  exports.prototype['numRegistrants'] = undefined;
  /**
   * @member {Array.<module:model/InlineResponse2008ResultRounds>} rounds
   */
  exports.prototype['rounds'] = undefined;



  return exports;
}));


