/**
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApChallengeMicroservice) {
      root.ApChallengeMicroservice = {};
    }
    root.ApChallengeMicroservice.InlineResponse20010ResultContent = factory(root.ApChallengeMicroservice.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineResponse20010ResultContent model module.
   * @module model/InlineResponse20010ResultContent
   * @version 1.0.5
   */

  /**
   * Constructs a new <code>InlineResponse20010ResultContent</code>.
   * @alias module:model/InlineResponse20010ResultContent
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>InlineResponse20010ResultContent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20010ResultContent} obj Optional instance to populate.
   * @return {module:model/InlineResponse20010ResultContent} The populated <code>InlineResponse20010ResultContent</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('userId')) {
        obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
      }
      if (data.hasOwnProperty('oldRating')) {
        obj['oldRating'] = ApiClient.convertToType(data['oldRating'], 'String');
      }
      if (data.hasOwnProperty('newRating')) {
        obj['newRating'] = ApiClient.convertToType(data['newRating'], 'String');
      }
      if (data.hasOwnProperty('rated')) {
        obj['rated'] = ApiClient.convertToType(data['rated'], 'String');
      }
      if (data.hasOwnProperty('roomPlacement')) {
        obj['roomPlacement'] = ApiClient.convertToType(data['roomPlacement'], 'String');
      }
      if (data.hasOwnProperty('division')) {
        obj['division'] = ApiClient.convertToType(data['division'], 'String');
      }
      if (data.hasOwnProperty('finalPoints')) {
        obj['finalPoints'] = ApiClient.convertToType(data['finalPoints'], 'String');
      }
      if (data.hasOwnProperty('divisionPlacement')) {
        obj['divisionPlacement'] = ApiClient.convertToType(data['divisionPlacement'], 'String');
      }
      if (data.hasOwnProperty('overallRank')) {
        obj['overallRank'] = ApiClient.convertToType(data['overallRank'], 'String');
      }
      if (data.hasOwnProperty('contestId')) {
        obj['contestId'] = ApiClient.convertToType(data['contestId'], 'String');
      }
    }
    return obj;
  }

  /**
   * the user id
   * @member {String} userId
   */
  exports.prototype['userId'] = undefined;
  /**
   * the old rating
   * @member {String} oldRating
   */
  exports.prototype['oldRating'] = undefined;
  /**
   * the new rating
   * @member {String} newRating
   */
  exports.prototype['newRating'] = undefined;
  /**
   * whether this SRM is rated
   * @member {module:model/InlineResponse20010ResultContent.RatedEnum} rated
   */
  exports.prototype['rated'] = undefined;
  /**
   * the room placement
   * @member {String} roomPlacement
   */
  exports.prototype['roomPlacement'] = undefined;
  /**
   * the division
   * @member {module:model/InlineResponse20010ResultContent.DivisionEnum} division
   */
  exports.prototype['division'] = undefined;
  /**
   * the final points
   * @member {String} finalPoints
   */
  exports.prototype['finalPoints'] = undefined;
  /**
   * the division placement
   * @member {String} divisionPlacement
   */
  exports.prototype['divisionPlacement'] = undefined;
  /**
   * the overall rank
   * @member {String} overallRank
   */
  exports.prototype['overallRank'] = undefined;
  /**
   * the contest id
   * @member {String} contestId
   */
  exports.prototype['contestId'] = undefined;


  /**
   * Allowed values for the <code>rated</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RatedEnum = {
    /**
     * value: "0"
     * @const
     */
    "0": "0",
    /**
     * value: "1"
     * @const
     */
    "1": "1"  };

  /**
   * Allowed values for the <code>division</code> property.
   * @enum {String}
   * @readonly
   */
  exports.DivisionEnum = {
    /**
     * value: "1"
     * @const
     */
    "1": "1",
    /**
     * value: "2"
     * @const
     */
    "2": "2"  };


  return exports;
}));


