/**
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApChallengeMicroservice) {
      root.ApChallengeMicroservice = {};
    }
    root.ApChallengeMicroservice.InlineResponse2007ResultUserMMDetails = factory(root.ApChallengeMicroservice.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineResponse2007ResultUserMMDetails model module.
   * @module model/InlineResponse2007ResultUserMMDetails
   * @version 1.0.5
   */

  /**
   * Constructs a new <code>InlineResponse2007ResultUserMMDetails</code>.
   * @alias module:model/InlineResponse2007ResultUserMMDetails
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>InlineResponse2007ResultUserMMDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2007ResultUserMMDetails} obj Optional instance to populate.
   * @return {module:model/InlineResponse2007ResultUserMMDetails} The populated <code>InlineResponse2007ResultUserMMDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('contestId')) {
        obj['contestId'] = ApiClient.convertToType(data['contestId'], 'Integer');
      }
      if (data.hasOwnProperty('roundId')) {
        obj['roundId'] = ApiClient.convertToType(data['roundId'], 'Integer');
      }
      if (data.hasOwnProperty('oldRating')) {
        obj['oldRating'] = ApiClient.convertToType(data['oldRating'], 'Integer');
      }
      if (data.hasOwnProperty('newRating')) {
        obj['newRating'] = ApiClient.convertToType(data['newRating'], 'Integer');
      }
      if (data.hasOwnProperty('rated')) {
        obj['rated'] = ApiClient.convertToType(data['rated'], 'Integer');
      }
      if (data.hasOwnProperty('pointTotal')) {
        obj['pointTotal'] = ApiClient.convertToType(data['pointTotal'], 'Integer');
      }
      if (data.hasOwnProperty('ovarallRank')) {
        obj['ovarallRank'] = ApiClient.convertToType(data['ovarallRank'], 'Integer');
      }
      if (data.hasOwnProperty('numSubmissions')) {
        obj['numSubmissions'] = ApiClient.convertToType(data['numSubmissions'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * @member {Integer} contestId
   */
  exports.prototype['contestId'] = undefined;
  /**
   * @member {Integer} roundId
   */
  exports.prototype['roundId'] = undefined;
  /**
   * @member {Integer} oldRating
   */
  exports.prototype['oldRating'] = undefined;
  /**
   * @member {Integer} newRating
   */
  exports.prototype['newRating'] = undefined;
  /**
   * @member {Integer} rated
   */
  exports.prototype['rated'] = undefined;
  /**
   * @member {Integer} pointTotal
   */
  exports.prototype['pointTotal'] = undefined;
  /**
   * @member {Integer} ovarallRank
   */
  exports.prototype['ovarallRank'] = undefined;
  /**
   * @member {Integer} numSubmissions
   */
  exports.prototype['numSubmissions'] = undefined;



  return exports;
}));


