/**
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApChallengeMicroservice);
  }
}(this, function(expect, ApChallengeMicroservice) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApChallengeMicroservice.DirectChallenge();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DirectChallenge', function() {
    it('should create an instance of DirectChallenge', function() {
      // uncomment below and update the code to test DirectChallenge
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be.a(ApChallengeMicroservice.DirectChallenge);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property challengeName (base name: "challengeName")', function() {
      // uncomment below and update the code to test the property challengeName
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property challengeType (base name: "challengeType")', function() {
      // uncomment below and update the code to test the property challengeType
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property clientName (base name: "clientName")', function() {
      // uncomment below and update the code to test the property clientName
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property clientId (base name: "clientId")', function() {
      // uncomment below and update the code to test the property clientId
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property billingName (base name: "billingName")', function() {
      // uncomment below and update the code to test the property billingName
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property billingId (base name: "billingId")', function() {
      // uncomment below and update the code to test the property billingId
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property directProjectName (base name: "directProjectName")', function() {
      // uncomment below and update the code to test the property directProjectName
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property directProjectId (base name: "directProjectId")', function() {
      // uncomment below and update the code to test the property directProjectId
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property challengeTechnologies (base name: "challengeTechnologies")', function() {
      // uncomment below and update the code to test the property challengeTechnologies
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property challengePlatforms (base name: "challengePlatforms")', function() {
      // uncomment below and update the code to test the property challengePlatforms
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property challengeStartDate (base name: "challengeStartDate")', function() {
      // uncomment below and update the code to test the property challengeStartDate
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property challengeEndDate (base name: "challengeEndDate")', function() {
      // uncomment below and update the code to test the property challengeEndDate
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property challengeStatus (base name: "challengeStatus")', function() {
      // uncomment below and update the code to test the property challengeStatus
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property challengeCreator (base name: "challengeCreator")', function() {
      // uncomment below and update the code to test the property challengeCreator
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property prizes (base name: "prizes")', function() {
      // uncomment below and update the code to test the property prizes
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property checkPointPrizes (base name: "checkPointPrizes")', function() {
      // uncomment below and update the code to test the property checkPointPrizes
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property totalPrize (base name: "totalPrize")', function() {
      // uncomment below and update the code to test the property totalPrize
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property drPoints (base name: "drPoints")', function() {
      // uncomment below and update the code to test the property drPoints
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property reliabilityBonus (base name: "reliabilityBonus")', function() {
      // uncomment below and update the code to test the property reliabilityBonus
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property challengeFee (base name: "challengeFee")', function() {
      // uncomment below and update the code to test the property challengeFee
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

    it('should have the property reviewCost (base name: "reviewCost")', function() {
      // uncomment below and update the code to test the property reviewCost
      //var instane = new ApChallengeMicroservice.DirectChallenge();
      //expect(instance).to.be();
    });

  });

}));
