/**
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApChallengeMicroservice);
  }
}(this, function(expect, ApChallengeMicroservice) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApChallengeMicroservice.InlineResponse2002ResultContent();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2002ResultContent', function() {
    it('should create an instance of InlineResponse2002ResultContent', function() {
      // uncomment below and update the code to test InlineResponse2002ResultContent
      //var instane = new ApChallengeMicroservice.InlineResponse2002ResultContent();
      //expect(instance).to.be.a(ApChallengeMicroservice.InlineResponse2002ResultContent);
    });

    it('should have the property phaseType (base name: "phaseType")', function() {
      // uncomment below and update the code to test the property phaseType
      //var instane = new ApChallengeMicroservice.InlineResponse2002ResultContent();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new ApChallengeMicroservice.InlineResponse2002ResultContent();
      //expect(instance).to.be();
    });

    it('should have the property fixedStarTime (base name: "fixedStarTime")', function() {
      // uncomment below and update the code to test the property fixedStarTime
      //var instane = new ApChallengeMicroservice.InlineResponse2002ResultContent();
      //expect(instance).to.be();
    });

    it('should have the property scheduledStarTime (base name: "scheduledStarTime")', function() {
      // uncomment below and update the code to test the property scheduledStarTime
      //var instane = new ApChallengeMicroservice.InlineResponse2002ResultContent();
      //expect(instance).to.be();
    });

    it('should have the property scheduledEndTime (base name: "scheduledEndTime")', function() {
      // uncomment below and update the code to test the property scheduledEndTime
      //var instane = new ApChallengeMicroservice.InlineResponse2002ResultContent();
      //expect(instance).to.be();
    });

    it('should have the property actualStartTime (base name: "actualStartTime")', function() {
      // uncomment below and update the code to test the property actualStartTime
      //var instane = new ApChallengeMicroservice.InlineResponse2002ResultContent();
      //expect(instance).to.be();
    });

    it('should have the property actualEndTime (base name: "actualEndTime")', function() {
      // uncomment below and update the code to test the property actualEndTime
      //var instane = new ApChallengeMicroservice.InlineResponse2002ResultContent();
      //expect(instance).to.be();
    });

    it('should have the property duration (base name: "duration")', function() {
      // uncomment below and update the code to test the property duration
      //var instane = new ApChallengeMicroservice.InlineResponse2002ResultContent();
      //expect(instance).to.be();
    });

  });

}));
