/**
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApChallengeMicroservice);
  }
}(this, function(expect, ApChallengeMicroservice) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApChallengeMicroservice.InlineResponse200ResultSubmissions();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse200ResultSubmissions', function() {
    it('should create an instance of InlineResponse200ResultSubmissions', function() {
      // uncomment below and update the code to test InlineResponse200ResultSubmissions
      //var instane = new ApChallengeMicroservice.InlineResponse200ResultSubmissions();
      //expect(instance).to.be.a(ApChallengeMicroservice.InlineResponse200ResultSubmissions);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new ApChallengeMicroservice.InlineResponse200ResultSubmissions();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new ApChallengeMicroservice.InlineResponse200ResultSubmissions();
      //expect(instance).to.be();
    });

    it('should have the property score (base name: "score")', function() {
      // uncomment below and update the code to test the property score
      //var instane = new ApChallengeMicroservice.InlineResponse200ResultSubmissions();
      //expect(instance).to.be();
    });

    it('should have the property placement (base name: "placement")', function() {
      // uncomment below and update the code to test the property placement
      //var instane = new ApChallengeMicroservice.InlineResponse200ResultSubmissions();
      //expect(instance).to.be();
    });

    it('should have the property challengeId (base name: "challengeId")', function() {
      // uncomment below and update the code to test the property challengeId
      //var instane = new ApChallengeMicroservice.InlineResponse200ResultSubmissions();
      //expect(instance).to.be();
    });

    it('should have the property submissionImage (base name: "submissionImage")', function() {
      // uncomment below and update the code to test the property submissionImage
      //var instane = new ApChallengeMicroservice.InlineResponse200ResultSubmissions();
      //expect(instance).to.be();
    });

    it('should have the property submittedAt (base name: "submittedAt")', function() {
      // uncomment below and update the code to test the property submittedAt
      //var instane = new ApChallengeMicroservice.InlineResponse200ResultSubmissions();
      //expect(instance).to.be();
    });

  });

}));
