/**
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApChallengeMicroservice);
  }
}(this, function(expect, ApChallengeMicroservice) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApChallengeMicroservice.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('activateChallenge', function() {
      it('should call activateChallenge successfully', function(done) {
        //uncomment below and update the code to test activateChallenge
        //instance.activateChallenge(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cancelPrivateContest', function() {
      it('should call cancelPrivateContest successfully', function(done) {
        //uncomment below and update the code to test cancelPrivateContest
        //instance.cancelPrivateContest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('challengeResultsGet', function() {
      it('should call challengeResultsGet successfully', function(done) {
        //uncomment below and update the code to test challengeResultsGet
        //instance.challengeResultsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('challengesGet', function() {
      it('should call challengesGet successfully', function(done) {
        //uncomment below and update the code to test challengesGet
        //instance.challengesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('challengesIdResourcesDelete', function() {
      it('should call challengesIdResourcesDelete successfully', function(done) {
        //uncomment below and update the code to test challengesIdResourcesDelete
        //instance.challengesIdResourcesDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('challengesIdResourcesGet', function() {
      it('should call challengesIdResourcesGet successfully', function(done) {
        //uncomment below and update the code to test challengesIdResourcesGet
        //instance.challengesIdResourcesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('challengesIdResourcesPost', function() {
      it('should call challengesIdResourcesPost successfully', function(done) {
        //uncomment below and update the code to test challengesIdResourcesPost
        //instance.challengesIdResourcesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('closePrivateContest', function() {
      it('should call closePrivateContest successfully', function(done) {
        //uncomment below and update the code to test closePrivateContest
        //instance.closePrivateContest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('marathonMatcheResultsGet', function() {
      it('should call marathonMatcheResultsGet successfully', function(done) {
        //uncomment below and update the code to test marathonMatcheResultsGet
        //instance.marathonMatcheResultsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('marathonMatchesGet', function() {
      it('should call marathonMatchesGet successfully', function(done) {
        //uncomment below and update the code to test marathonMatchesGet
        //instance.marathonMatchesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('membersHandleChallengesGet', function() {
      it('should call membersHandleChallengesGet successfully', function(done) {
        //uncomment below and update the code to test membersHandleChallengesGet
        //instance.membersHandleChallengesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('membersHandleMmsGet', function() {
      it('should call membersHandleMmsGet successfully', function(done) {
        //uncomment below and update the code to test membersHandleMmsGet
        //instance.membersHandleMmsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('membersHandleSrmsGet', function() {
      it('should call membersHandleSrmsGet successfully', function(done) {
        //uncomment below and update the code to test membersHandleSrmsGet
        //instance.membersHandleSrmsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('phasesGet', function() {
      it('should call phasesGet successfully', function(done) {
        //uncomment below and update the code to test phasesGet
        //instance.phasesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('platformsGet', function() {
      it('should call platformsGet successfully', function(done) {
        //uncomment below and update the code to test platformsGet
        //instance.platformsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('platformsIdDelete', function() {
      it('should call platformsIdDelete successfully', function(done) {
        //uncomment below and update the code to test platformsIdDelete
        //instance.platformsIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('platformsIdPatch', function() {
      it('should call platformsIdPatch successfully', function(done) {
        //uncomment below and update the code to test platformsIdPatch
        //instance.platformsIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('platformsPost', function() {
      it('should call platformsPost successfully', function(done) {
        //uncomment below and update the code to test platformsPost
        //instance.platformsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('saveDraftContest', function() {
      it('should call saveDraftContest successfully', function(done) {
        //uncomment below and update the code to test saveDraftContest
        //instance.saveDraftContest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('srmResultsGet', function() {
      it('should call srmResultsGet successfully', function(done) {
        //uncomment below and update the code to test srmResultsGet
        //instance.srmResultsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('srmsGet', function() {
      it('should call srmsGet successfully', function(done) {
        //uncomment below and update the code to test srmsGet
        //instance.srmsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('technologiesGet', function() {
      it('should call technologiesGet successfully', function(done) {
        //uncomment below and update the code to test technologiesGet
        //instance.technologiesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('technologiesIdDelete', function() {
      it('should call technologiesIdDelete successfully', function(done) {
        //uncomment below and update the code to test technologiesIdDelete
        //instance.technologiesIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('technologiesIdPatch', function() {
      it('should call technologiesIdPatch successfully', function(done) {
        //uncomment below and update the code to test technologiesIdPatch
        //instance.technologiesIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('technologiesPost', function() {
      it('should call technologiesPost successfully', function(done) {
        //uncomment below and update the code to test technologiesPost
        //instance.technologiesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
